import {
  SiNextdotjs,
  SiReact,
  SiPrisma,
  SiPostgresql,
  SiMongodb,
  SiTypescript,
  SiZod,
  SiStripe,
  SiVercel,
  SiTailwindcss,
  SiFramer,
  SiAuth0,
  SiNodedotjs,
  SiGit,
  SiGithubactions,
  SiDocker,
  SiRedis,
  SiJsonwebtokens,
  SiDrizzle,
  SiSqlite,
  SiMysql,
  SiLucia,
  SiPython,
  SiJavascript,
  SiGitlab,
  SiKubernetes,
} from "react-icons/si";

export const techCategories = [
  {
    title: "Frontend",
    items: [
      { name: "Next.js", icon: SiNextdotjs },
      { name: "React", icon: SiReact },
      { name: "TypeScript", icon: SiTypescript },
      { name: "JavaScript", icon: SiJavascript },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "Framer Motion", icon: SiFramer },
    ],
  },
  {
    title: "Backend",
    items: [
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Prisma ORM", icon: SiPrisma },
      { name: "PostgreSQL", icon: SiPostgresql },
      { name: "MongoDB", icon: SiMongodb },
      { name: "Redis", icon: SiRedis },
      { name: "Python", icon: SiPython },
    ],
  },
  {
    title: "Development",
    items: [
      { name: "TypeScript", icon: SiTypescript },
      { name: "Zod", icon: SiZod },
      { name: "Git", icon: SiGit },
      { name: "GitHub Actions", icon: SiGithubactions },
      { name: "Docker", icon: SiDocker },
    ],
  },
  {
    title: "Database",
    items: [
      { name: "PostgreSQL", icon: SiPostgresql },
      { name: "MongoDB", icon: SiMongodb },
      { name: "SQL Lite", icon: SiSqlite },
      { name: "MySQL", icon: SiMysql },
      { name: "Prisma ORM", icon: SiPrisma },
      { name: "Drizzle", icon: SiDrizzle },
    ],
  },
  {
    title: "DevOps",
    items: [
      { name: "Vercel", icon: SiVercel },
      { name: "Docker", icon: SiDocker },
      { name: "GitLab", icon: SiGitlab },
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Kubernetes", icon: SiKubernetes },
      { name: "Git", icon: SiGit },
    ],
  },
  {
    title: "Security",
    items: [
      { name: "Auth0", icon: SiAuth0 },
      { name: "JWT", icon: SiJsonwebtokens },
      { name: "Stripe", icon: SiStripe },
      { name: "TypeScript", icon: SiTypescript },
      { name: "Lucia", icon: SiLucia },
      { name: "Zod", icon: SiZod },
    ],
  },
];
